---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup nginx base installation
- name: Install nginx
  become: true
  package:
    name: nginx
    state: present

- name: Remove nginx default site
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create nginx config directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/nginx/nginxconfig.io
    - /etc/nginx/sites-enabled

- name: Template out nginx base config files
  become: true
  template:
    src: templates/{{ item }}
    dest: /etc/nginx/{{ item }}
    mode: 0644
  loop:
    - nginx.conf
    - nginxconfig.io/general.conf
    - nginxconfig.io/proxy.conf
    - nginxconfig.io/security.conf
  notify: Reload nginx

- name: Create Diffie-Hellman keys
  command: openssl dhparam -out /etc/nginx/dhparam.pem 2048
  args:
    creates: /etc/nginx/dhparam.pem

# Configure reverse proxy sites
- name: Template out reverse proxy sites
  template:
    src: templates/reverseproxy.conf.j2
    dest: /etc/nginx/sites-enabled/{{ item.domain }}.conf
    mode: 0644
  vars:
    site_domain: "{{ item.domain }}"
    proxy_url: "{{ item.proxy_url }}"
    client_ca_cert: "{{ item.client_ca_cert | default(None) }}"
    use_proxy_host: "{{ item.use_proxy_host | default(False) }}"
    use_by_default: "{{ item.use_by_default | default(False) }}"
  loop: "{{ sites }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.type == "proxy"
  notify: Reload nginx

# Configure static site
- name: Template out static sites
  template:
    src: templates/staticsite.conf.j2
    dest: /etc/nginx/sites-enabled/{{ item.domain }}.conf
    mode: 0644
  vars:
    site_domain: "{{ item.domain }}"
    site_root: "{{ item.root }}"
    client_ca_cert: "{{ item.client_ca_cert | default(None) }}"
    use_by_default: "{{ item.use_by_default | default(False) }}"
  loop: "{{ sites }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.type == "static"
  notify: Reload nginx
