---
# Setup nginx base installation
- name: Install nginx
  become: True
  apt:
    name: nginx
    state: present
    update_cache: True
    cache_valid_time: 86400

- name: Create nginx config directories
  become: True
  file:
    path: /etc/nginx/nginxconfig.io
    state: directory

- name: Template out nginx base config files
  become: True
  template:
    src: templates/{{ item }}
    dest: /etc/nginx/{{ item }}
  loop:
    - nginx.conf
    - nginxconfig.io/general.conf
    - nginxconfig.io/proxy.conf
    - nginxconfig.io/security.conf

- name: Create Diffie-Hellman keys
  command: openssl dhparam -out /etc/nginx/dhparam.pem 2048
  args:
    creates: /etc/nginx/dhparam.pem

# Configure reverse proxy sites
- name: Template out reverse proxy sites
  template:
    src: templates/reverseproxy.conf.j2
    dest: /etc/nginx/sites-enabled/{{ item.domain }}.conf
  vars:
    site_domain: "{{ item.domain }}"
    proxy_url: "{{ item.proxy_url }}"
  loop: "{{ sites }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.type == "proxy"

# Configure static site
- name: Template out static sites
  template:
    src: templates/staticsite.conf.j2
    dest: /etc/nginx/sites-enabled/{{ item.domain }}.conf
  vars:
    site_domain: "{{ item.domain }}"
    site_root: "{{ item.root }}"
  loop: "{{ sites }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.type == "static"

# Configure backups
## TODO
