---
- name: Converge
  hosts: all
  become: true
  roles:
    # Apply the role from the top-level directory name rather than hardcoding
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        server_cert: /etc/ssl/certs/molecule-cert.pem
        server_cert_key: /etc/ssl/private/molecule-cert.key
        sites:
          - name: demo
            type: static
            domain: demo.example
            root: /opt/demosite
            extra_config: |
              autoindex on;
          - name: demoproxy
            type: proxy
            domain: proxy.example
            proxy_url: http://example.com
            use_proxy_host: true  # We need this because example.com is external
            use_by_default: true
          - name: insecure_static
            type: static
            domain: insecure.example
            root: /opt/demosite
            allow_insecure: true
          - name: insecure_proxy
            type: proxy
            domain: insecure_proxy.example
            proxy_url: http://example.com
            use_proxy_host: true  # We need this because example.com is external
            allow_insecure: true

          # Test both types with a client certificate
          - name: cert-static
            type: static
            domain: static.cert.example
            root: /opt/demosite
            client_ca_cert: /etc/ssl/certs/fake-client-ca.crt
          - name: cert-proxy
            type: proxy
            domain: proxy.cert.example
            proxy_url: https://example.com
            client_ca_cert: /etc/ssl/certs/fake-client-ca.crt
            use_proxy_host: true  # We need this because example.com is external
