---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance
    image: leandelivery/docker-systemd:ubuntu-18.04
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    etc_hosts:
      "demo.example": "127.0.0.1"
      "proxy.example": "127.0.0.1"
      "static.cert.example": "127.0.0.1"
      "proxy.cert.example": "127.0.0.1"
    published_ports:
      - "443"
    capabilities:
      - SYS_ADMIN
    privileged: true
provisioner:
  name: ansible
scenario:
  name: default
