---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  # Ignore role name when linting
  ansible-lint -x 106
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: ${MOLECULE_DOCKER_COMMAND:-""}  # systemd won't work if this is left to molecule's default
    pre_build_image: true
    etc_hosts:
      "demo.example": "127.0.0.1"
      "proxy.example": "127.0.0.1"
      "insecure.example": "127.0.0.1"
      "insecure_proxy.example": "127.0.0.1"
      "static.cert.example": "127.0.0.1"
      "proxy.cert.example": "127.0.0.1"
    published_ports:
      - "443"
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
