---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Create somewhere for static site to live
      file:
        dest: /opt/demosite
        state: directory
    - name: Drop out a rubbish static site
      copy:
        content: <html><head></head><body><h1>Demo Site</h1></body></html>
        dest: /opt/demosite/index.html
    - name: Install curl to view the site
      apt:
        name: curl
        state: present
        update_cache: true
        cache_valid_time: 86400
    - name: Add sample sites to hosts file
      lineinfile:
        line: 127.0.0.1 demo.example. proxy.example.
        path: /etc/hosts
        state: present
    - name: Install snakeoil certs
      apt:
        name: ssl-cert
        state: present
