---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Create somewhere for static site to live
      file:
        dest: /opt/demosite
        state: directory
    - name: Drop out a rubbish static site
      copy:
        content: <html><head></head><body><h1>Demo Site</h1></body></html>
        dest: /opt/demosite/index.html
    - name: Install curl to view the site
      apt:
        name: curl
        state: present
        update_cache: true
        cache_valid_time: 86400
    - name: Install snakeoil certs
      apt:
        name: ssl-cert
        state: present

    - name: Create nginx config directory to enable fake key installation
      file:
        path: /etc/nginx/
        state: directory

    - name: Install "fake" Diffie-Hellman keys, because we know that bit works!
      copy:
        src: resources/dhparam.pem
        dest: /etc/nginx/dhparam.pem

    - name: Generate a "fake" CA and client cert on the Ansible controller
      become: false
      delegate_to: 127.0.0.1
      command: ./make-fake-cert.sh
      args:
        chdir: resources

    - name: Copy the CA to the remote system
      copy:
        src: resources/generated-certs/fake-client-ca.crt
        dest: /etc/ssl/certs/fake-client-ca.crt
