---
name: CI with Molecule
"on":
  push:
  workflow_dispatch:
  # Build master every Tuesday at 7AM (schedule only applies to the master branch)
  schedule:
    - cron: "0 7 * * 2"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install deps
        run: pip3 install ansible ansible-lint molecule[docker]

      - name: Check syntax
        run: molecule syntax
      - name: Create instances, prepare environment
        run: molecule create && molecule prepare
      - name: Apply the role to the instance, run tests
        run: molecule converge
      - name: Check the role is idempotent
        run: molecule idempotence
      - name: Clean up instance
        run: molecule destroy
